# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org'
 platform :ios, '9.0'

target 'DevelopDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod "SDWebImage"
  pod 'Masonry'
end
